version: '3'

services:
  web:
    build: .
    volumes:
      - './:/app'
    ports:
      - '3000:3000'
      - '3001:3001'
    env_file: '.env'
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres/archiver'
      S3_ENDPOINT: 'http://s3:8000'
      S3_ACCESS_KEY_ID: test
      S3_SECRET_ACCESS_KEY: test
      S3_BUCKET: slack-archiver-files
    command: yarn dev

  s3:
    image: 'zenko/cloudserver'
    environment:
      SCALITY_ACCESS_KEY_ID: test
      SCALITY_SECRET_ACCESS_KEY: test
      REMOTE_MANAGEMENT_DISABLE: '1'
      ENDPOINT: 's3:8000'
    volumes:
      - s3_data:/usr/src/app/localData
      - s3_metadata:/usr/src/app/localMetadata

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: archiver
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  s3_data:
  s3_metadata:
