version: '3'

services:
  web:
    build: .
    volumes:
      - './:/app'
    ports:
      - '3001:3000'
    env_file: '.env'
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@postgres/archiver'
    command: yarn dev

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: archiver

